### ISSUE TITLE
Why is the sequence length increasing as the auto-regressive decoding progresses?

### ISSUE THREAD

**Issue by TheTinyTeddy** [test-time-training/ttt-lm-pytorch#17]
Hi,

I was wondering in the code why is the sequence length increases as more tokens are predicted, since this is similar to how transformer decoder does inference.

My understanding of TTT is that it is a RNN with a per token weight update mechanism, but the sequence length should always be 1. Could you tell me if I am missing something?

**Comment by Kerrypinny** [comment]
Hello @TheTinyTeddy 
 It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team 
Please see the link below to our dedicated support line:
[ Support Requests team ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by xvjiarui** [comment]
Hi @TheTinyTeddy 
Thanks for your interest in our work. Your desired behavior needs to set up cache during decoding. To enable this, you need to set `configuration = TTTConfig(use_cache=True)`. Please let me know if this resolve your issue.

**Comment by TheTinyTeddy** [comment]
Thank you for the reply!

So is there a similar notion of "KV cache" in TTT, just like in Transformer decoder?

**Comment by xvjiarui** [comment]
Yes. But the cache size doesn't increase with sequence length. It's fixed size like any other RNN
