### ISSUE TITLE
The current code doesn't load any model.

### ISSUE THREAD

**Issue by MeNicefellow** [test-time-training/ttt-lm-pytorch#20]

**Comment by karan-dalal** [comment]
This code is just for inference.

**Comment by MeNicefellow** [comment]
> This code is just for inference. 

For inference, you need to load the checkpoint first, or it is randomly initialized. How can you infer with that?

**Comment by karan-dalal** [comment]
You can use our JAX codebase to train a model, then load it into PyTorch.

**Comment by MeNicefellow** [comment]
> You can use our JAX codebase to train a model, then load it into PyTorch.

But you already have trained models here https://huggingface.co/Test-Time-Training. Why don't you show how to load them?

**Comment by Z-Z188** [comment]
> > You can use our JAX codebase to train a model, then load it into PyTorch.
> 
> But you already have trained models here https://huggingface.co/Test-Time-Training. Why don't you show how to load them?

Hello, author! I have the same question. Could you teach us how to load the train models?

**Comment by karan-dalal** [comment]
https://github.com/test-time-training/ttt-lm-pytorch/issues/22

**Comment by MeNicefellow** [comment]
@karan-dalal That is about converting to Pytorch. I wonder why it is so hard for you to provide the complete example code to load the model in pytorch and perform inference by updating the example in the README.md file. Your model is such a different thing from existing models, a user friendly example would be so helpful!

**Comment by karan-dalal** [comment]
Our model wraps the HuggingFace PreTrained class. Once you convert the PyTorch checkpoint, you can simply load with something like:

```python
  model = TttForCausalLM.from_pretrained(
      pt_args.weight_path,
      torch_dtype=torch.float32,
      device_map="auto",
      **pt_args.model_args,
  )
```

**Comment by helldog-star** [comment]
> Our model wraps the HuggingFace PreTrained class. Once you convert the PyTorch checkpoint, you can simply load with something like:
> 
> ```python
>   model = TttForCausalLM.from_pretrained(
>       pt_args.weight_path,
>       torch_dtype=torch.float32,
>       device_map="auto",
>       **pt_args.model_args,
>   )
> ```

The latest version of transformers does not have the 'ttt' model, nor does it contain the 'TttForCausalLM' class. Could you please provide the version of transformers you are using? Or could you provide the code for 'TttForCausalLM'?
