### ISSUE TITLE
 The multiplication of matrix

### ISSUE THREAD

**Issue by Z-Z188** [test-time-training/ttt-lm-pytorch#23]
![image](https://github.com/user-attachments/assets/01d98a57-90a1-420b-a698-8574eff567bc)
Hello author, thank you very much for your work. But I have a problem with the multiplication of this matrix: if X is a matrix of size (d,b), then the transpose of X x X has size (b, b), and WX-X has size (d, b), then how can the two matrices be multiplied? Look forward to your reply, thank you!

**Comment by karan-dalal** [comment]
This was a typo in an earlier submission. The updated equation is on Arxiv. https://arxiv.org/pdf/2407.04620 
<img width="634" alt="Screenshot 2024-09-08 at 12 02 57 AM" src="https://github.com/user-attachments/assets/e46771b5-a74f-4d94-9dd5-4b4b65b8c6d6">

**Comment by Z-Z188** [comment]
> This was a typo in an earlier submission. The updated equation is on Arxiv. https://arxiv.org/pdf/2407.04620 <img alt="Screenshot 2024-09-08 at 12 02 57 AM" width="634" src="https://private-user-images.githubusercontent.com/44450861/365420063-e46771b5-a74f-4d94-9dd5-4b4b65b8c6d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3Nzk0NTcsIm5iZiI6MTcyNTc3OTE1NywicGF0aCI6Ii80NDQ1MDg2MS8zNjU0MjAwNjMtZTQ2NzcxYjUtYTc0Zi00ZDk0LTlkZDUtNGI0YjY1YjhjNmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA3MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OTE4YzVkM2Q1NzgwYWUwZThlZmVmZWM2NTE5NDZiODAzOGIzNDQ5MjFiNmRiMzk3ZWMyYWI5NjBmNTliZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wMofqR1oz-D_PIGvhNG6UZaZo_QIFuBmbBiWVsQKHmY">

Thanks！
