### ISSUE TITLE
the meaning of the formula

### ISSUE THREAD

**Issue by Z-Z188** [test-time-training/ttt-lm-pytorch#25]
![image](https://github.com/user-attachments/assets/3b97c84f-9455-4bac-940f-701065b4a9d4)
Hello author, thank you for your work. What are these formulas for? Are there any corresponding places in the article? Look forward to your reply, thank you!

**Comment by karan-dalal** [comment]
Yes, see the dual form derivation section in the appendix. This formula is the gradient of layernorm w.r.t L2 loss.

**Comment by Z-Z188** [comment]
> Yes, see the dual form derivation section in the appendix. This formula is the gradient of layernorm w.r.t L2 loss.

May I ask what formula in the appendix is implemented by this code?
