### ISSUE TITLE
Accelerating Torch trainging for TTT

### ISSUE THREAD

**Issue by jongjyh** [test-time-training/ttt-lm-pytorch#26]
Hi, authors!

Thank you for open-source such a great project. I would like to know how to accelerate the training speed of TTT-torch. 

Also, What may cause the speed diff between Torch and Jax?

Looking forward to your reply. Thanks!

Best regards.

**Comment by karan-dalal** [comment]
JAX just-in-time compilation is pretty good. We're working on training speed and will release something soon.
