### ISSUE TITLE
The definition of Context Length

### ISSUE THREAD

**Issue by Z-Z188** [test-time-training/ttt-lm-pytorch#27]
![image](https://github.com/user-attachments/assets/6d277d27-5091-4a5b-8b3c-a2ef1c8508b7)
Hello author, thank you for your work. So how is this context length defined? Is one word corresponding to one token, and the corresponding length is 1? That's a lot to say for a 32k sentence. Looking forward to the author's answer, thank you!

**Comment by karan-dalal** [comment]
The context length is # of tokens. A token can be 1 word or a section of a word, depending on its type.

**Comment by Z-Z188** [comment]
Hello author, can you give a specific example? I still don't understand. Look forward to your reply, thank you!
