### ISSUE TITLE
The coding about reconstruction_target 

### ISSUE THREAD

**Issue by ZhaoqiZachYang** [test-time-training/ttt-lm-pytorch#32]
In line 970 of the file ttt.py, the reconstruction_target is calculated as XV_mini_batch - XK_mini_batch. However, in the paper, the reconstruction_target is set just as XV_mini_batch. Why do we use the subtraction in the code?

**Comment by karan-dalal** [comment]
We use a residual connection for stability that can be interpreted as changing the reconstruction target.
