### ISSUE TITLE
Related works

### ISSUE THREAD

**Issue by kiriyamashinnji** [test-time-training/ttt-lm-pytorch#7]
Great work about combining test time learning with RNNs. It seems that the idea of this work is closely related to [With Greater Text Comes Greater Necessity: Inference-Time Training Helps Long Text Generation](https://arxiv.org/pdf/2401.11504), which trains a LoRA at test time to memorize the past input.

**Comment by karan-dalal** [comment]
Interesting, thanks for sharing.
