### ISSUE TITLE
How to use TTTLinear/TTTMLP like RNNs

### ISSUE THREAD

**Issue by zx1292982431** [test-time-training/ttt-lm-pytorch#9]
How can I use TTTLinear/TTTMLP to perform time series modeling for data in the shape of [B, T, C], just like using RNN? Could you give me a sample?

**Comment by LeoXinhaoLee** [comment]
Hi, thanks for your question. TTT layers are essentially RNN blocks. So if you can use an RNN for your application, you should be able to use TTT layers as well.

**Comment by zx1292982431** [comment]
Thanks for your reply! I init a TTTLinear and try to forward like:
```
from ttt import TTTForCausalLM, TTTConfig, TTT_STANDARD_CONFIGS,TTTLinear
import torch

configuration = TTTConfig()

model = TTTLinear(configuration,layer_idx=0)
X =  torch.rand(1,101,2048) #[B,T,C]
Y = model(X)
```
but I got the error :
```
Traceback (most recent call last):
  File "/home/lizixuan/workspace/projects/tmp_coding/TTTtest.py", line 8, in <module>
    Y = model(X)
  File "/home/lizixuan/miniconda3/envs/lzx/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lizixuan/miniconda3/envs/lzx/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/raid2/user_space/lizixuan/projects/tmp_coding/ttt.py", line 869, in forward
    cos, sin = self.rotary_emb(XV, position_ids % self.mini_batch_size)
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
```
I notice that the ` position_ids  ` is optional, is it necessary? Please point me out where I am wrong. Thanks again.

**Comment by LeoXinhaoLee** [comment]
Specific to this paper, we use rope positional embedding to distinguish different **positions in one TTT mini-batch** (and in this paper, there's only 16 positions in there), which empirically improves performance a bit. 

Therefore, the TTTLinear and TTTMLP modules in this code require `position_ids`, which is generated here: 
https://github.com/test-time-training/ttt-lm-pytorch/blob/4ddc7732cae4ac44884804ef9febf2a9a435c3f8/ttt.py#L1454

**Comment by Dushuai12138** [comment]
I try to use TTTmodel
···
from transformers import AutoTokenizer
from ttt import TTTForCausalLM, TTTConfig, TTT_STANDARD_CONFIGS
configuration = TTTConfig()
model4 = TTTModel(configuration).to("cuda")
print(model4)
import torch
batch_size, length, dim1 = 1, 20, 2048
x = torch.randint(0,10,(batch_size, length, dim1)).to("cuda")
model4.train()
y = model4(x)
···
and get error:
···
File /scratch/yyzha/dushuai/SMPre/jupyter/ttt.py:865, in TTTBase.forward(self, hidden_states, attention_mask, position_ids, cache_params)
    862 XQ, XK, XV = self.get_qkv_projections(hidden_states, cache_params=cache_params)
    864 # [B, L, C] -> [B, L, num_heads, head_dim] -> [B, num_heads, L, head_dim]
--> 865 XQ = XQ.reshape(B, L, self.num_heads, self.head_dim).transpose(1, 2)
    866 XK = XK.reshape(B, L, self.num_heads, self.head_dim).transpose(1, 2)
    867 XV = XV.reshape(B, L, self.num_heads, self.head_dim).transpose(1, 2)

RuntimeError: shape '[1, 20, 32, 64]' is invalid for input of size 83886080
···

**Comment by LeoXinhaoLee** [comment]
Hi, I think it's because our language model is defined to take in token indices as input, so the input shape should be `[B, T]`, where each element is the id of a token. Please see https://github.com/test-time-training/ttt-lm-pytorch/blob/4ddc7732cae4ac44884804ef9febf2a9a435c3f8/ttt.py#L1446

**Comment by Sjun1017** [comment]
Traceback (most recent call last):
  File "/home/lab532/sj/Vim-main/Vim-main/vim/main.py", line 550, in <module>
    main(args)
  File "/home/lab532/sj/Vim-main/Vim-main/vim/main.py", line 481, in main
    train_stats = train_one_epoch(
  File "/home/lab532/sj/Vim-main/Vim-main/vim/engine.py", line 157, in train_one_epoch
    loss.backward()
  File "/home/lab532/anaconda3/envs/vmamba/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/lab532/anaconda3/envs/vmamba/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 24, 24]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
Hi could you help me deal this problem？ thank you

**Comment by KEH0T0** [comment]
> Traceback (most recent call last): File "/home/lab532/sj/Vim-main/Vim-main/vim/main.py", line 550, in main(args) File "/home/lab532/sj/Vim-main/Vim-main/vim/main.py", line 481, in main train_stats = train_one_epoch( File "/home/lab532/sj/Vim-main/Vim-main/vim/engine.py", line 157, in train_one_epoch loss.backward() File "/home/lab532/anaconda3/envs/vmamba/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward torch.autograd.backward( File "/home/lab532/anaconda3/envs/vmamba/lib/python3.10/site-packages/torch/autograd/**init**.py", line 251, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 24, 24]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck! Hi could you help me deal this problem？ thank you

Hi, Did you solve this issue?
